name: DailyTask2 vs. DailyTask
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      # format as "v3.3.80-rc.0" (worked for pyappify-action >=1.1.0)
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
  workflow_dispatch:
jobs:
  daily-task-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Check Files Existence
        id: check_files
        run: |
          FILE1="src/task/DailyTask.py"
          FILE2="src/task/DailyTask2.py"
          #
          if [ ! -f "$FILE1" ] || [ ! -f "$FILE2" ]; then
            echo "Error: One or both files do not exist."
            exit 1
          fi
          if cmp -s "$FILE1" "$FILE2"; then
            echo "Files are identical. No diff needed."
            echo "FILES_IDENTICAL=true" >> $GITHUB_ENV
          else
            echo "Files are different. Generating diff."
            echo "FILES_IDENTICAL=false" >> $GITHUB_ENV
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      - name: Install Diff2html
        if: env.FILES_IDENTICAL == 'false'
        run: |
          sudo npm install -g diff2html-cli@5.2.15
      - name: Cache npm global packages
        if: env.FILES_IDENTICAL == 'false'
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-global-diff2html-cli-5.2.15
      - name: Generate Diff HTML
        if: env.FILES_IDENTICAL == 'false'
        run: |
          FILE1="src/task/DailyTask.py"
          FILE2="src/task/DailyTask2.py"
          OUTPUT_FILE="readme/DailyTask.diff.html"
          #
          mkdir -p readme
          diff -u "$FILE1" "$FILE2" | diff2html --style side --input "stdin" --file "$OUTPUT_FILE"
          echo "Diff report has been generated at '$OUTPUT_FILE'."
      - name: Commit and Push
        if: env.FILES_IDENTICAL == 'false'
        run: |
          cd $GITHUB_WORKSPACE
          git add --renormalize readme/DailyTask.diff.html
          if ! git diff-index --quiet HEAD --; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "update file readme/DailyTask.diff.html" readme/DailyTask.diff.html
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main
            echo "Changes of file 'readme/DailyTask.diff.html' has been committed and pushed."
          else
            echo "No changes is found in file 'readme/DailyTask.diff.html'."
          fi
